# Default model to use as fallback when no valid model is found
default_model: "gpt-3.5-turbo"

agent:
  content-gen:
    model: "gemini-2.0-flash-lite"
    temperature: 0.7
    max_tokens: 1500
    iter: 5

  eval:
    model: "gemini-2.0-flash-lite"
    temperature: 0.3
    max_tokens: 2000

  code-gen:
    model: "gemini-2.0-flash-lite"
    temperature: 0.5
    max_tokens: 2000

output:
  format: "docx"

improv-rate: 3
