# Default model to use as fallback when no valid model is found
default_model: "gpt-3.5-turbo"

agent:
  content-gen:
    model: "gpt-4.1-nano"
    temperature: 0.7
    max_tokens: 1500
    iter: 5

  eval:
    model: "gpt-4"
    temperature: 0.3
    max_tokens: 1000

  code-gen:
    model: "gpt-4"
    temperature: 0.5
    max_tokens: 2000

output:
  format: "docx"
